RunWait '"C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe"'
  . ' /in "destiny2-junk-dismantler.ahk"'
  . ' /out "destiny2-junk-dismantler.exe"'
  . ' /base "C:\Program Files\AutoHotkey\v2\AutoHotkey64.exe"'
  . ' /compress 0'